/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.publics;


import edu.java.jooq.DefaultCatalog;
import edu.java.jooq.publics.tables.ChatsToLinks;
import edu.java.jooq.publics.tables.ContentByLink;
import edu.java.jooq.publics.tables.Databasechangelog;
import edu.java.jooq.publics.tables.Databasechangeloglock;
import edu.java.jooq.publics.tables.Links;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.chats_to_links</code>.
     */
    public final ChatsToLinks CHATS_TO_LINKS = ChatsToLinks.CHATS_TO_LINKS;

    /**
     * The table <code>public.content_by_link</code>.
     */
    public final ContentByLink CONTENT_BY_LINK = ContentByLink.CONTENT_BY_LINK;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.links</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ChatsToLinks.CHATS_TO_LINKS,
            ContentByLink.CONTENT_BY_LINK,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Links.LINKS
        );
    }
}
