/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.publics;


import edu.java.jooq.publics.tables.ChatsToLinks;
import edu.java.jooq.publics.tables.ContentByLink;
import edu.java.jooq.publics.tables.Databasechangelog;
import edu.java.jooq.publics.tables.Databasechangeloglock;
import edu.java.jooq.publics.tables.Links;
import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.chats_to_links</code>.
     */
    public static final ChatsToLinks CHATS_TO_LINKS = ChatsToLinks.CHATS_TO_LINKS;

    /**
     * The table <code>public.content_by_link</code>.
     */
    public static final ContentByLink CONTENT_BY_LINK = ContentByLink.CONTENT_BY_LINK;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.links</code>.
     */
    public static final Links LINKS = Links.LINKS;
}
