app:
  database-access-type: jdbc
  scheduler:
    enable: true
    update-time: 5
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto=update
    show-sql=true
    properties.hibernate.format_sql=true
    properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 8080
  link: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml
