app:
  database-access-type: jpa
  scheduler:
    enable: true
    update-time: 5
    interval: 10s
    force-check-delay: 10s
  backoff:
    policy: const
    max-attempts: 3
    delay: 1s
    supported-codes:
      - 400
      - 404
      - 500
  ratelimit:
    capacity: 1000
    period: 60s
  github-link: https://api.github.com/repos/
  stackoverflow-link: https://api.stackexchange.com/2.3/questions/
  link-update-transfer-type: kafka
  kafka:
    addresses: "localhost:29091,localhost:29092,localhost:29093"
    link-update-topic: "messages.links_update"

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate.ddl-auto=validate
    show-sql=true
    properties.hibernate.format_sql=true
    properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 8080
  link: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8092
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics

  metrics:
    tags:
      application: ${spring.application.name}
