app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:scrapper
    username: postgres
    password: postgres

server:
  port: 8080
  link: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml
