app:
  telegram-token: unset
  kafka:
    addresses: "localhost:29091,localhost:29092,localhost:29093"
    link-update-topic: "messages.links_update"
    link-update-group: "messages-group"
    concurrency: "1"
  ratelimit:
    capacity: 1000
    period: 60s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090
  link: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics

  metrics:
    tags:
      application: ${spring.application.name}
