app:
  telegram-token: unset
  kafka:
    addresses: "localhost:29091,localhost:29092,localhost:29093"
    link-update-topic: "messages.links_update"
    link-update-group: "messages-group"
    concurrency: "1"
  ratelimit:
    capacity: 1000
    period: 60s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:scrapper
    username: postgres
    password: postgres

server:
  port: 8090
  link: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml
