app:
  telegram-token: unset
  ratelimit:
    capacity: 1000
    period: 60s

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:scrapper
    username: postgres
    password: postgres

server:
  port: 8090
  link: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml
