/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.publics.tables;

import edu.java.jooq.publics.Public;
import java.time.LocalDateTime;
import java.util.Collection;
import javax.annotation.processing.Generated;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContentByLink extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.content_by_link</code>
     */
    public static final ContentByLink CONTENT_BY_LINK = new ContentByLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.content_by_link.link_id</code>.
     */
    public final TableField<Record, Long> LINK_ID = createField(DSL.name("link_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.content_by_link.content</code>.
     */
    public final TableField<Record, String> CONTENT = createField(DSL.name("content"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.content_by_link.updated_at</code>.
     */
    public final TableField<Record, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private ContentByLink(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ContentByLink(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.content_by_link</code> table reference
     */
    public ContentByLink(String alias) {
        this(DSL.name(alias), CONTENT_BY_LINK);
    }

    /**
     * Create an aliased <code>public.content_by_link</code> table reference
     */
    public ContentByLink(Name alias) {
        this(alias, CONTENT_BY_LINK);
    }

    /**
     * Create a <code>public.content_by_link</code> table reference
     */
    public ContentByLink() {
        this(DSL.name("content_by_link"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(ContentByLink.CONTENT_BY_LINK, DSL.name("content_by_link_pkey"), new TableField[] { ContentByLink.CONTENT_BY_LINK.LINK_ID }, true);
    }

    @Override
    public ContentByLink as(String alias) {
        return new ContentByLink(DSL.name(alias), this);
    }

    @Override
    public ContentByLink as(Name alias) {
        return new ContentByLink(alias, this);
    }

    @Override
    public ContentByLink as(Table<?> alias) {
        return new ContentByLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentByLink rename(String name) {
        return new ContentByLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentByLink rename(Name name) {
        return new ContentByLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentByLink rename(Table<?> name) {
        return new ContentByLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentByLink where(Condition condition) {
        return new ContentByLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentByLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentByLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentByLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentByLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentByLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentByLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentByLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentByLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentByLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
