package edu.java.clients;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class Utils {
    public static String GITHUB_TEST_RESPONSE =
        """
            [
              {
                "id": 16822682753,
                "node_id": "PSH_kwLOGwQzH88AAAAD6rXEgQ",
                "before": "18234e40d98ea4e27561b6b4ebd14590fc330c39",
                "after": "604c5d02a880f690ba4e9221027721e42c7db2cd",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-27T19:09:00Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16822590343,
                "node_id": "PSH_kwLOGwQzH88AAAAD6rRbhw",
                "before": "7603b99eff408e41dee6e2b76b3f0145ae3aa1d1",
                "after": "18234e40d98ea4e27561b6b4ebd14590fc330c39",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-27T18:53:22Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729331882,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SVYqg",
                "before": "e902ea747a4a6c3d348a0dbb5538bee4811dc757",
                "after": "7603b99eff408e41dee6e2b76b3f0145ae3aa1d1",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:29:55Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729329848,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SVQuA",
                "before": "cd0802cc070e493b065fd102b465e0a3f2b7175b",
                "after": "e902ea747a4a6c3d348a0dbb5538bee4811dc757",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:29:34Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729327705,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SVIWQ",
                "before": "96b3ab3d5d00ab7dff2770b7dc140473a13f244b",
                "after": "cd0802cc070e493b065fd102b465e0a3f2b7175b",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:29:12Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729325663,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SVAXw",
                "before": "48c6fe50b9fc8b9ca89914ec0c101a1a08004d1c",
                "after": "96b3ab3d5d00ab7dff2770b7dc140473a13f244b",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:28:53Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729323507,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SU38w",
                "before": "c49fcba078704f7f2f6a7dde0f50a46d2b9a223b",
                "after": "48c6fe50b9fc8b9ca89914ec0c101a1a08004d1c",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:28:33Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729320941,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SUt7Q",
                "before": "cdb8c78a4a74632bc273d084a560b1ca53d918f8",
                "after": "c49fcba078704f7f2f6a7dde0f50a46d2b9a223b",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:28:09Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16729317984,
                "node_id": "PSH_kwLOGwQzH88AAAAD5SUiYA",
                "before": "542991091289669dfa71016be30f0de3169d19dc",
                "after": "cdb8c78a4a74632bc273d084a560b1ca53d918f8",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-21T14:27:42Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662664048,
                "node_id": "PSH_kwLOGwQzH88AAAAD4SwTcA",
                "before": "ee0a2124c3ad501576cfaaec855eda05babf3126",
                "after": "542991091289669dfa71016be30f0de3169d19dc",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:59:34Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662554807,
                "node_id": "PSH_kwLOGwQzH88AAAAD4Spotw",
                "before": "85a4048d669ea0a266d6821d06ee3beec7e5f1d3",
                "after": "ee0a2124c3ad501576cfaaec855eda05babf3126",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:52:39Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662413432,
                "node_id": "PSH_kwLOGwQzH88AAAAD4ShAeA",
                "before": "efbcbb53d4beedefffa9afc4cbce5e1f7ef1184e",
                "after": "85a4048d669ea0a266d6821d06ee3beec7e5f1d3",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:43:42Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662395826,
                "node_id": "PSH_kwLOGwQzH88AAAAD4Sf7sg",
                "before": "1f405ac5d5d589e6c490aa9f84eecbdf44f707cf",
                "after": "efbcbb53d4beedefffa9afc4cbce5e1f7ef1184e",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:42:35Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662380757,
                "node_id": "PSH_kwLOGwQzH88AAAAD4SfA1Q",
                "before": "3d9491d8704794c316f321343d6e1883ad21b259",
                "after": "1f405ac5d5d589e6c490aa9f84eecbdf44f707cf",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:41:37Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662323071,
                "node_id": "PSH_kwLOGwQzH88AAAAD4Sbffw",
                "before": "c5a26d1ef5faa9b5183725f6b65ca764fc401a00",
                "after": "3d9491d8704794c316f321343d6e1883ad21b259",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:37:56Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 16662310700,
                "node_id": "PSH_kwLOGwQzH88AAAAD4SavLA",
                "before": "6fff309cf7b8c4d93b85af49c5e2e345bcf4da8b",
                "after": "c5a26d1ef5faa9b5183725f6b65ca764fc401a00",
                "ref": "refs/heads/main",
                "timestamp": "2024-01-16T15:37:09Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 14248038457,
                "node_id": "PSH_kwLOGwQzH88AAAADUT_QOQ",
                "before": "8b3b05e41932209887dbf1fd2e2acfe7692f15c4",
                "after": "6fff309cf7b8c4d93b85af49c5e2e345bcf4da8b",
                "ref": "refs/heads/main",
                "timestamp": "2023-07-08T04:01:04Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 14045507039,
                "node_id": "PSH_kwLOGwQzH88AAAADRS1t3w",
                "before": "77812d3f2711b4c236fe9fab3d40d4c434c41737",
                "after": "8b3b05e41932209887dbf1fd2e2acfe7692f15c4",
                "ref": "refs/heads/main",
                "timestamp": "2023-06-20T12:11:48Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              },
              {
                "id": 14045465845,
                "node_id": "PSH_kwLOGwQzH88AAAADRSzM9Q",
                "before": "6cbc5423eb5885221e6395d570b7f2e2e7796058",
                "after": "77812d3f2711b4c236fe9fab3d40d4c434c41737",
                "ref": "refs/heads/main",
                "timestamp": "2023-06-20T12:08:43Z",
                "activity_type": "push",
                "actor": {
                  "login": "Nypiaka",
                  "id": 98625721,
                  "node_id": "U_kgDOBeDouQ",
                  "avatar_url": "https://avatars.githubusercontent.com/u/98625721?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/Nypiaka",
                  "html_url": "https://github.com/Nypiaka",
                  "followers_url": "https://api.github.com/users/Nypiaka/followers",
                  "following_url": "https://api.github.com/users/Nypiaka/following{/other_user}",
                  "gists_url": "https://api.github.com/users/Nypiaka/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/Nypiaka/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/Nypiaka/subscriptions",
                  "organizations_url": "https://api.github.com/users/Nypiaka/orgs",
                  "repos_url": "https://api.github.com/users/Nypiaka/repos",
                  "events_url": "https://api.github.com/users/Nypiaka/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/Nypiaka/received_events",
                  "type": "User",
                  "site_admin": false
                }
              }
            ]
            """;
    public static String STACKOVERFLOW_TEST_RESPONSE = """
        {
           "items":[
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1703116800,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1699315200,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1697500800,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":3057654,
                    "reputation":5565,
                    "user_id":2590960,
                    "user_type":"registered",
                    "accept_rate":54,
                    "profile_image":"https://i.stack.imgur.com/OxUCS.jpg?s=256&g=1",
                    "display_name":"grep",
                    "link":"https://stackoverflow.com/users/2590960/grep"
                 },
                 "creation_date":1697414400,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":51333059,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":11928123,
                    "reputation":677,
                    "user_id":8728821,
                    "user_type":"registered",
                    "profile_image":"https://www.gravatar.com/avatar/0f7b7d3daf10b1da2b9a20092b8f9609?s=256&d=identicon&r=PG&f=y&so-version=2",
                    "display_name":"Sagar Ahuja",
                    "link":"https://stackoverflow.com/users/8728821/sagar-ahuja"
                 },
                 "creation_date":1697068800,
                 "down_vote_count":0,
                 "up_vote_count":2,
                 "post_id":59209846,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":13678404,
                    "reputation":454,
                    "user_id":9869329,
                    "user_type":"registered",
                    "profile_image":"https://graph.facebook.com/2080470682193672/picture?type=large",
                    "display_name":"Purushotham CK",
                    "link":"https://stackoverflow.com/users/9869329/purushotham-ck"
                 },
                 "creation_date":1696774813,
                 "comment_id":136193605,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"comment"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1696723200,
                 "down_vote_count":1,
                 "up_vote_count":0,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":936447,
                    "reputation":2921,
                    "user_id":965294,
                    "user_type":"registered",
                    "accept_rate":32,
                    "profile_image":"https://www.gravatar.com/avatar/84fed36429de1948901f9a2be656e434?s=256&d=identicon&r=PG",
                    "display_name":"jsf",
                    "link":"https://stackoverflow.com/users/965294/jsf"
                 },
                 "creation_date":1696464000,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15250928,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":140637,
                    "reputation":6204,
                    "user_id":1311394,
                    "user_type":"registered",
                    "profile_image":"https://www.gravatar.com/avatar/1cb1c20979a4dfe4c3eceaf53d855bbc?s=256&d=identicon&r=PG",
                    "display_name":"ach",
                    "link":"https://stackoverflow.com/users/1311394/ach"
                 },
                 "creation_date":1696464000,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15252365,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1696464000,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":936447,
                    "reputation":2921,
                    "user_id":965294,
                    "user_type":"registered",
                    "accept_rate":32,
                    "profile_image":"https://www.gravatar.com/avatar/84fed36429de1948901f9a2be656e434?s=256&d=identicon&r=PG",
                    "display_name":"jsf",
                    "link":"https://stackoverflow.com/users/965294/jsf"
                 },
                 "creation_date":1694908800,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15250928,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":140637,
                    "reputation":6204,
                    "user_id":1311394,
                    "user_type":"registered",
                    "profile_image":"https://www.gravatar.com/avatar/1cb1c20979a4dfe4c3eceaf53d855bbc?s=256&d=identicon&r=PG",
                    "display_name":"ach",
                    "link":"https://stackoverflow.com/users/1311394/ach"
                 },
                 "creation_date":1692144000,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15252365,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":11928123,
                    "reputation":677,
                    "user_id":8728821,
                    "user_type":"registered",
                    "profile_image":"https://www.gravatar.com/avatar/0f7b7d3daf10b1da2b9a20092b8f9609?s=256&d=identicon&r=PG&f=y&so-version=2",
                    "display_name":"Sagar Ahuja",
                    "link":"https://stackoverflow.com/users/8728821/sagar-ahuja"
                 },
                 "creation_date":1691648472,
                 "comment_id":135520334,
                 "post_id":59209846,
                 "question_id":15250928,
                 "timeline_type":"comment"
              },
              {
                 "owner":{
                    "account_id":161394,
                    "reputation":1955,
                    "user_id":382115,
                    "user_type":"registered",
                    "accept_rate":78,
                    "profile_image":"https://www.gravatar.com/avatar/e55cc1d06fb3a833a582f72ce2863e48?s=256&d=identicon&r=PG",
                    "display_name":"Maxrunner",
                    "link":"https://stackoverflow.com/users/382115/maxrunner"
                 },
                 "creation_date":1691603537,
                 "comment_id":135515279,
                 "post_id":68747876,
                 "question_id":15250928,
                 "timeline_type":"comment"
              },
              {
                 "owner":{
                    "account_id":161394,
                    "reputation":1955,
                    "user_id":382115,
                    "user_type":"registered",
                    "accept_rate":78,
                    "profile_image":"https://www.gravatar.com/avatar/e55cc1d06fb3a833a582f72ce2863e48?s=256&d=identicon&r=PG",
                    "display_name":"Maxrunner",
                    "link":"https://stackoverflow.com/users/382115/maxrunner"
                 },
                 "creation_date":1691603162,
                 "comment_id":135515207,
                 "post_id":59209846,
                 "question_id":15250928,
                 "timeline_type":"comment"
              },
              {
                 "owner":{
                    "account_id":936447,
                    "reputation":2921,
                    "user_id":965294,
                    "user_type":"registered",
                    "accept_rate":32,
                    "profile_image":"https://www.gravatar.com/avatar/84fed36429de1948901f9a2be656e434?s=256&d=identicon&r=PG",
                    "display_name":"jsf",
                    "link":"https://stackoverflow.com/users/965294/jsf"
                 },
                 "creation_date":1689811200,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15250928,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1689811200,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":936447,
                    "reputation":2921,
                    "user_id":965294,
                    "user_type":"registered",
                    "accept_rate":32,
                    "profile_image":"https://www.gravatar.com/avatar/84fed36429de1948901f9a2be656e434?s=256&d=identicon&r=PG",
                    "display_name":"jsf",
                    "link":"https://stackoverflow.com/users/965294/jsf"
                 },
                 "creation_date":1681430400,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15250928,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":140637,
                    "reputation":6204,
                    "user_id":1311394,
                    "user_type":"registered",
                    "profile_image":"https://www.gravatar.com/avatar/1cb1c20979a4dfe4c3eceaf53d855bbc?s=256&d=identicon&r=PG",
                    "display_name":"ach",
                    "link":"https://stackoverflow.com/users/1311394/ach"
                 },
                 "creation_date":1681430400,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15252365,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1681430400,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":936447,
                    "reputation":2921,
                    "user_id":965294,
                    "user_type":"registered",
                    "accept_rate":32,
                    "profile_image":"https://www.gravatar.com/avatar/84fed36429de1948901f9a2be656e434?s=256&d=identicon&r=PG",
                    "display_name":"jsf",
                    "link":"https://stackoverflow.com/users/965294/jsf"
                 },
                 "creation_date":1680652800,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":15250928,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1679616000,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":14245148,
                    "reputation":1055,
                    "user_id":10582056,
                    "user_type":"registered",
                    "profile_image":"https://i.stack.imgur.com/iImfb.jpg?s=256&g=1",
                    "display_name":"ahrooran",
                    "link":"https://stackoverflow.com/users/10582056/ahrooran"
                 },
                 "creation_date":1678873870,
                 "comment_id":133616026,
                 "post_id":59209846,
                 "question_id":15250928,
                 "timeline_type":"comment"
              },
              {
                 "owner":{
                    "account_id":11928123,
                    "reputation":677,
                    "user_id":8728821,
                    "user_type":"registered",
                    "profile_image":"https://www.gravatar.com/avatar/0f7b7d3daf10b1da2b9a20092b8f9609?s=256&d=identicon&r=PG&f=y&so-version=2",
                    "display_name":"Sagar Ahuja",
                    "link":"https://stackoverflow.com/users/8728821/sagar-ahuja"
                 },
                 "creation_date":1678838400,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":59209846,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1668211200,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1661904000,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1661385600,
                 "down_vote_count":1,
                 "up_vote_count":0,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":936447,
                    "reputation":2921,
                    "user_id":965294,
                    "user_type":"registered",
                    "accept_rate":32,
                    "profile_image":"https://www.gravatar.com/avatar/84fed36429de1948901f9a2be656e434?s=256&d=identicon&r=PG",
                    "display_name":"jsf",
                    "link":"https://stackoverflow.com/users/965294/jsf"
                 },
                 "creation_date":1660780800,
                 "down_vote_count":0,
                 "up_vote_count":2,
                 "post_id":15250928,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1660780800,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              },
              {
                 "owner":{
                    "account_id":93689,
                    "reputation":418053,
                    "user_id":256196,
                    "user_type":"moderator",
                    "accept_rate":77,
                    "profile_image":"https://www.gravatar.com/avatar/d84b558fd67be10d5a718fb94231909d?s=256&d=identicon&r=PG",
                    "display_name":"Bohemian",
                    "link":"https://stackoverflow.com/users/256196/bohemian"
                 },
                 "creation_date":1655337600,
                 "down_vote_count":0,
                 "up_vote_count":1,
                 "post_id":31109486,
                 "question_id":15250928,
                 "timeline_type":"vote_aggregate"
              }
           ],
           "has_more":true,
           "quota_max":300,
           "quota_remaining":118
        }
        """;
}
